"""
constants.py — Справочник всех 100 тикеров с секторами.
"""

TICKER_NAMES: dict[str, tuple[str, str]] = {
    # ── Technology (10) ──────────────────────────────────────────
    "AAPL":  ("Apple Inc.",                   "Technology"),
    "MSFT":  ("Microsoft Corporation",         "Technology"),
    "GOOGL": ("Alphabet Inc.",                 "Technology"),
    "NVDA":  ("NVIDIA Corporation",            "Technology"),
    "META":  ("Meta Platforms Inc.",           "Technology"),
    "AVGO":  ("Broadcom Inc.",                 "Technology"),
    "ORCL":  ("Oracle Corporation",            "Technology"),
    "CRM":   ("Salesforce Inc.",               "Technology"),
    "ADBE":  ("Adobe Inc.",                    "Technology"),
    "INTC":  ("Intel Corporation",             "Technology"),
    # ── Technology — semiconductors ──────────────────────────────
    "QCOM":  ("Qualcomm Inc.",                 "Technology"),
    "NOW":   ("ServiceNow Inc.",               "Technology"),
    "AMD":   ("Advanced Micro Devices",        "Technology"),
    "AMAT":  ("Applied Materials Inc.",        "Technology"),
    "TXN":   ("Texas Instruments Inc.",        "Technology"),
    "LRCX":  ("Lam Research Corporation",      "Technology"),
    "KLAC":  ("KLA Corporation",               "Technology"),
    "MU":    ("Micron Technology Inc.",        "Technology"),
    "CDNS":  ("Cadence Design Systems",        "Technology"),
    "SNPS":  ("Synopsys Inc.",                 "Technology"),
    # ── Financial Services (10) ──────────────────────────────────
    "JPM":   ("JPMorgan Chase & Co.",          "Financial Services"),
    "V":     ("Visa Inc.",                     "Financial Services"),
    "MA":    ("Mastercard Inc.",               "Financial Services"),
    "BAC":   ("Bank of America Corp.",         "Financial Services"),
    "GS":    ("Goldman Sachs Group Inc.",      "Financial Services"),
    "WFC":   ("Wells Fargo & Company",         "Financial Services"),
    "MS":    ("Morgan Stanley",                "Financial Services"),
    "BLK":   ("BlackRock Inc.",                "Financial Services"),
    "SPGI":  ("S&P Global Inc.",               "Financial Services"),
    "AXP":   ("American Express Company",      "Financial Services"),
    "CB":    ("Chubb Limited",                 "Financial Services"),
    "PGR":   ("Progressive Corporation",       "Financial Services"),
    "CME":   ("CME Group Inc.",                "Financial Services"),
    "BRK-B": ("Berkshire Hathaway Inc.",       "Financial Services"),
    # ── Healthcare (10) ──────────────────────────────────────────
    "JNJ":   ("Johnson & Johnson",             "Healthcare"),
    "UNH":   ("UnitedHealth Group Inc.",       "Healthcare"),
    "LLY":   ("Eli Lilly and Company",         "Healthcare"),
    "AMGN":  ("Amgen Inc.",                    "Healthcare"),
    "PFE":   ("Pfizer Inc.",                   "Healthcare"),
    "TMO":   ("Thermo Fisher Scientific",      "Healthcare"),
    "MRK":   ("Merck & Co. Inc.",              "Healthcare"),
    "ABT":   ("Abbott Laboratories",           "Healthcare"),
    "DHR":   ("Danaher Corporation",           "Healthcare"),
    "VRTX":  ("Vertex Pharmaceuticals",        "Healthcare"),
    "ISRG":  ("Intuitive Surgical Inc.",       "Healthcare"),
    "BSX":   ("Boston Scientific Corp.",       "Healthcare"),
    "SYK":   ("Stryker Corporation",           "Healthcare"),
    "REGN":  ("Regeneron Pharmaceuticals",     "Healthcare"),
    # ── Consumer Cyclical (8) ────────────────────────────────────
    "AMZN":  ("Amazon.com Inc.",               "Consumer Cyclical"),
    "TSLA":  ("Tesla Inc.",                    "Consumer Cyclical"),
    "HD":    ("Home Depot Inc.",               "Consumer Cyclical"),
    "BKNG":  ("Booking Holdings Inc.",         "Consumer Cyclical"),
    "LOW":   ("Lowe's Companies Inc.",         "Consumer Cyclical"),
    "TJX":   ("TJX Companies Inc.",            "Consumer Cyclical"),
    "NKE":   ("Nike Inc.",                     "Consumer Cyclical"),
    "SBUX":  ("Starbucks Corporation",         "Consumer Cyclical"),
    "ABNB":  ("Airbnb Inc.",                   "Consumer Cyclical"),
    "EBAY":  ("eBay Inc.",                     "Consumer Cyclical"),
    # ── Consumer Defensive (6) ───────────────────────────────────
    "PG":    ("Procter & Gamble Co.",          "Consumer Defensive"),
    "KO":    ("Coca-Cola Company",             "Consumer Defensive"),
    "WMT":   ("Walmart Inc.",                  "Consumer Defensive"),
    "PEP":   ("PepsiCo Inc.",                  "Consumer Defensive"),
    "COST":  ("Costco Wholesale Corp.",        "Consumer Defensive"),
    "MDLZ":  ("Mondelez International",        "Consumer Defensive"),
    "GM":    ("General Motors Company",        "Consumer Cyclical"),
    "F":     ("Ford Motor Company",            "Consumer Cyclical"),
    "MCD":   ("McDonald's Corporation",        "Consumer Defensive"),
    "CL":    ("Colgate-Palmolive Company",     "Consumer Defensive"),
    # ── Energy (6) ───────────────────────────────────────────────
    "XOM":   ("Exxon Mobil Corporation",       "Energy"),
    "CVX":   ("Chevron Corporation",           "Energy"),
    "COP":   ("ConocoPhillips",                "Energy"),
    "MPC":   ("Marathon Petroleum Corp.",      "Energy"),
    "EOG":   ("EOG Resources Inc.",            "Energy"),
    "PSX":   ("Phillips 66",                   "Energy"),
    "SLB":   ("SLB (Schlumberger)",            "Energy"),
    "OXY":   ("Occidental Petroleum Corp.",    "Energy"),
    # ── Industrials (8) ──────────────────────────────────────────
    "HON":   ("Honeywell International",       "Industrials"),
    "CAT":   ("Caterpillar Inc.",              "Industrials"),
    "BA":    ("Boeing Company",                "Industrials"),
    "LMT":   ("Lockheed Martin Corp.",         "Industrials"),
    "RTX":   ("RTX Corporation",               "Industrials"),
    "GE":    ("GE Aerospace",                  "Industrials"),
    "DE":    ("Deere & Company",               "Industrials"),
    "UPS":   ("United Parcel Service",         "Industrials"),
    "EMR":   ("Emerson Electric Co.",          "Industrials"),
    "NOC":   ("Northrop Grumman Corp.",        "Industrials"),
    "FDX":   ("FedEx Corporation",             "Industrials"),
    "ETN":   ("Eaton Corporation",             "Industrials"),
    # ── Communication Services (6) ───────────────────────────────
    "NFLX":  ("Netflix Inc.",                  "Communication Services"),
    "DIS":   ("The Walt Disney Company",       "Communication Services"),
    "CMCSA": ("Comcast Corporation",           "Communication Services"),
    "T":     ("AT&T Inc.",                     "Communication Services"),
    "VZ":    ("Verizon Communications",        "Communication Services"),
    "TMUS":  ("T-Mobile US Inc.",              "Communication Services"),
    # ── Real Estate (3) ──────────────────────────────────────────
    "PLD":   ("Prologis Inc.",                 "Real Estate"),
    "AMT":   ("American Tower Corp.",          "Real Estate"),
    "EQIX":  ("Equinix Inc.",                  "Real Estate"),
    # ── Utilities (3) ────────────────────────────────────────────
    "NEE":   ("NextEra Energy Inc.",           "Utilities"),
    "DUK":   ("Duke Energy Corporation",       "Utilities"),
    "SO":    ("Southern Company",              "Utilities"),
}

FALLBACK_TICKERS: list[str] = list(TICKER_NAMES.keys())
BOOTSTRAP_TICKERS: list[str] = FALLBACK_TICKERS.copy()
